farmer-web/farmer/urls.py
from django.contrib import admin
from django.urls import (
    include,
    path
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mgmt/', include('mgmt.urls', namespace='mgmt')),
    path('', include('front.urls', namespace='front')),
]

farmer-web/mgmt/urls.py
from django.urls import path

from . import views


app_name = 'mgmt'

urlpatterns = [
    # HTML / redirects
    path('', views.home, name="home"),
    path(
        'adm/edit_computer/<computer_cn>', views.edit_computer,
        name='edit_computer'
    ),

    path('adm/clear_errors', views.clear_errors, name='clear_errors'),
    path('adm/create_computer', views.create_computer, name='create_computer'),
    path('adm/create_server', views.create_server, name='create_server'),
    path('adm/create_user', views.create_user, name='create_user'),
    path('adm/create_variable', views.create_variable, name='create_variable'),
    path(
        'adm/create_variable/<computer_cn>', views.create_variable,
        name='create_variable'
    ),
    path(
        'adm/edit_computer/<computer_cn>', views.edit_computer,
        name='edit_computer'
    ),
    path('adm/edit_server/<server_id>', views.edit_server, name='edit_server'),
    path('adm/edit_user/<user_cn>', views.edit_user, name='edit_user'),
    path(
        'adm/edit_variable/<variable_id>', views.edit_variable,
        name='edit_variable'
    ),
    path(
        'adm/delete_variable/<variable_id>',
        views.delete_variable, name='delete_variable'
    ),
    path('adm/list_computers', views.list_computers, name='list_computers'),
    path('adm/list_errors', views.list_errors, name='list_errors'),
    path('adm/list_roles', views.list_roles, name='list_roles'),
    path('adm/list_servers', views.list_servers, name='list_servers'),
    path('adm/list_users', views.list_users, name='list_users'),
    path('adm/list_variables', views.list_variables, name='list_variables'),
    path('adm/reload_roles', views.reload_roles, name='reload_roles'),
    path(
        'adm/show_computer_dmesgs/<computer_cn>', views.show_computer_dmesgs,
        name='show_computer_dmesgs'
    ),
    path(
        'adm/show_computer_errors/<computer_cn>', views.show_computer_errors,
        name='show_computer_errors'
    ),
    path(
        'adm/show_computer_upgrades/<computer_cn>',
        views.show_computer_upgrades,
        name='show_computer_upgrades'
    ),
    path(
        'adm/show_stat/<computer_cn>/<stat_id>',
        views.show_stat, name='show_stat'
    ),
    path('adm/show_dmesg/<dmesg_id>', views.show_dmesg, name='show_dmesg'),
    path('adm/show_error/<error_id>', views.show_error, name='show_error'),
    path('adm/show_stats/<computer_cn>', views.show_stats, name='show_stats'),

    # HTML / redirects | allowed to simple users
    path('adm/show_user', views.show_user, name='show_user'),

    # JSON | allowed to computers
    path('get_computer_vars/<computer_cn>', views.get_computer_vars),
    path('get_playbook_inventory/<computer_cn>', views.get_playbook_inventory),
    path('post_address/<computer_cn>', views.post_address),
    path('post_stats/<computer_cn>', views.post_stats),
    path('post_error/<computer_cn>', views.post_error),
    path('post_dmesg/<computer_cn>', views.post_dmesg),
    path('post_upgrade/<computer_cn>', views.post_upgrade),
]

farmer-web/mgmt/forms.py
from django import forms

from . import models


class LdapUserForm(forms.ModelForm):
    class Meta:
        model = models.LdapUser
        fields = [
            'user_name',
            'full_name',
            'email',
            'phone',
            'postalAddress',
            'postalCode',
            'city',
            'password',
        ]
        widgets = {
            'email': forms.EmailInput(),
            'postalAddress': forms.Textarea(attrs={"cols": 40, "rows": 3}),
            'password': forms.PasswordInput(),
        }

    def __init__(self, servers=None, server=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        servers = (
            (server.id, server.nice_name)
            for server in servers
        )
        server = server.id if server is not None else 0
        self.fields['server'] = forms.ChoiceField(
            label="Serveur", widget=forms.RadioSelect,
            choices=servers, required=True, initial=server
        )

    password2 = forms.CharField(
        label="Mot de passe (confirmation)", widget=forms.PasswordInput,
        required=False
    )

    def clean(self):
        cleaned_data = super().clean()

        passwd = cleaned_data['password']
        passwd2 = cleaned_data['password2']

        if passwd != passwd2:
            raise forms.ValidationError(
                "Les mots de passe ne correspondent pas"
            )

        if not passwd.startswith(models.LDAP_HASH_PREFIX):
            passwd = models.compute_ldap_password_hash(passwd)
            cleaned_data['password'] = passwd
            cleaned_data['password2'] = passwd

        return cleaned_data


class LdapComputerForm(forms.ModelForm):
    class Meta:
        model = models.LdapComputer
        fields = [
            'user_name',
            'full_name',
            'long_description',
            'password',
        ]
        widgets = {
            'password': forms.PasswordInput(),
            'long_description': forms.Textarea(attrs={"cols": 60, "rows": 10}),
        }

    password2 = forms.CharField(
        label="Mot de passe (confirmation)", widget=forms.PasswordInput,
        required=False
    )
    users = forms.ModelMultipleChoiceField(
        queryset=models.LdapUser.objects.all()
    )
    roles = forms.ModelMultipleChoiceField(
        queryset=models.Role.objects.all()
    )

    def __init__(self, *args, users=[], roles=[], **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['users'] = forms.ModelMultipleChoiceField(
            queryset=models.LdapUser.objects.all(),
            widget=forms.SelectMultiple(attrs={
                'size': 15,
                'style': "width: 200px;"
            }),
            required=False,
            initial=users
        )
        self.fields['roles'] = forms.ModelMultipleChoiceField(
            queryset=models.Role.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=False,
            initial=roles
        )

    def clean(self):
        cleaned_data = super().clean()

        passwd = cleaned_data['password']
        passwd2 = cleaned_data['password2']

        if passwd != passwd2:
            raise forms.ValidationError(
                "Les mots de passe ne correspondent pas"
            )

        if not passwd.startswith(models.LDAP_HASH_PREFIX):
            passwd = models.compute_ldap_password_hash(passwd)
            cleaned_data['password'] = passwd
            cleaned_data['password2'] = passwd

        return cleaned_data


class StorageServerForm(forms.ModelForm):
    class Meta:
        model = models.StorageServer
        fields = [
            'address',
            'nice_name',
        ]


class VariableForm(forms.ModelForm):
    class Meta:
        model = models.Variable
        fields = [
            'computer_cn',
            'name',
            'value',
        ]

farmer-web/mgmt/views.py
import datetime
import json
import os
import random
import shutil
import string
import time

import dulwich.porcelain
import petname

from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse
)
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from . import forms
from . import models
from . import ppgen


def generate_passwords(length=16, nb_passwords=6):
    for _ in range(0, nb_passwords):
        characters = string.ascii_letters + string.digits
        yield "".join(random.choice(characters) for _ in range(length))


def get_next_ldap_uid_number(cls=models.LdapUser, default=10000):
    try:
        user = cls.objects.order_by("-uid")[0]
        return user.uid + 1
    except IndexError:
        return default


def get_storage_server_assignment(user):
    try:
        return models.StorageServerAssignment.objects.get(user_cn=user.cn)
    except models.StorageServerAssignment.DoesNotExist:
        return models.StorageServerAssignment(
            user_cn=user.cn,
            server=models.StorageServer.objects.order_by('nice_name')[0]
        )


@staff_member_required
def home(request):
    unread_errors = models.ErrorLog.objects.defer('content').filter(
        read=False
    ).count()
    return render(request, 'mgmt_home.html', {
        'unread_errors': unread_errors,
    })


@staff_member_required
def create_user(request):
    servers = models.StorageServer.objects.order_by('nice_name')
    if request.method == "POST":
        form = forms.LdapUserForm(servers, None, request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.cn = user.user_name
            user.home_directory = models.HOME_PATHS.format(user.user_name)
            user.uid = get_next_ldap_uid_number()
            user.group = 10000
            user.save()

            server_id = form.cleaned_data['server']
            server = models.StorageServer.objects.get(id=server_id)

            assign = get_storage_server_assignment(user)
            assign.server = server
            assign.save()

            return HttpResponseRedirect(
                redirect_to=reverse("mgmt:list_users")
            )
    else:
        form = forms.LdapUserForm(servers, None)
    return render(request, 'mgmt_user.html', {
        "name": "",
        "user": form,
        "target_url": reverse("mgmt:create_user"),
        "action": "Ajouter",
        "suggested_passwords":
            list(generate_passwords(12)) + list(ppgen.generate_passwords()),
    })


@staff_member_required
def edit_user(request, user_cn):
    servers = models.StorageServer.objects.order_by('nice_name')
    user = models.LdapUser.objects.get(cn=user_cn)
    assign = get_storage_server_assignment(user)
    computers = get_user_computers(user_cn)

    if request.method == "POST":
        passwd = user.password
        form = forms.LdapUserForm(
            servers, None, request.POST, instance=user
        )
        if form.is_valid():
            user = form.save(commit=False)
            user.cn = user.user_name
            user.home_directory = models.HOME_PATHS.format(user.user_name)
            if len(user.password) <= 0:
                user.password = passwd
            user.save()

            server_id = form.cleaned_data['server']
            assign.server = models.StorageServer.objects.get(id=server_id)
            assign.save()

            return HttpResponseRedirect(
                redirect_to=reverse("mgmt:list_users")
            )
    else:
        form = forms.LdapUserForm(
            servers, assign.server, instance=user
        )
    return render(request, 'mgmt_user.html', {
        "computers": computers,
        "name": user.user_name,
        "user": form,
        "target_url": reverse("mgmt:edit_user", args=[user.cn]),
        "action": "Modifier",
        "suggested_passwords":
            list(generate_passwords(12)) + list(ppgen.generate_passwords()),
    })


@staff_member_required
def list_users(request):
    users = models.LdapUser.objects.all()

    # we cannot sort LDAP objects in a case-insensitive manner using .extra()
    # so we do it manually
    users = [(u.full_name.lower(), idx, u) for (idx, u) in enumerate(users)]
    users.sort()
    users = [u[2] for u in users]

    return render(request, 'mgmt_users.html', {
        "users": users
    })


@staff_member_required
def list_errors(request):
    errors = models.ErrorLog.objects.all().defer('content').order_by(
        "-date"
    )[:50]
    return render(request, 'mgmt_errors.html', {
        "errors": errors
    })


@login_required
def show_error(request, error_id):
    error = models.ErrorLog.objects.get(id=error_id)
    if not request.user.is_staff:
        check_user_access(request, error.computer_cn)
    try:
        content = json.loads(error.content)
    except json.JSONDecodeError:
        content = error.content
    if request.user.is_staff:
        error.read = True
        error.save()
    return render(request, 'mgmt_error.html', {
        "name": error.computer_cn,
        "error": error,
        "content": content,
    })


@login_required
def show_dmesg(request, dmesg_id):
    dmesg = models.Dmesg.objects.get(id=dmesg_id)
    if not request.user.is_staff:
        check_user_access(request, dmesg.computer_cn)
    try:
        content = json.loads(dmesg.content)
    except json.JSONDecodeError:
        content = dmesg.content
    return render(request, 'mgmt_dmesg.html', {
        "name": dmesg.computer_cn,
        "dmesg": dmesg,
        "content": content,
    })


@staff_member_required
def clear_errors(request):
    models.ErrorLog.objects.all().update(read=True)
    return HttpResponseRedirect(
        redirect_to=reverse("mgmt:list_errors")
    )


@staff_member_required
def create_variable(request, computer_cn=""):
    if request.method == "POST":
        form = forms.VariableForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                redirect_to=reverse("mgmt:home")
            )
    else:
        form = forms.VariableForm(initial={
            'computer_cn': computer_cn,
        })

    return render(request, 'mgmt_variable.html', {
        "name": "",
        "variable": form,
        "target_url": reverse("mgmt:create_variable"),
        "action": "Ajouter",
    })


@staff_member_required
def edit_variable(request, variable_id):
    variable = models.Variable.objects.get(id=int(variable_id))
    if request.method == "POST":
        form = forms.VariableForm(request.POST, instance=variable)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                redirect_to=reverse("mgmt:home")
            )
    else:
        form = forms.VariableForm(instance=variable)
    return render(request, 'mgmt_variable.html', {
        "variable_id": str(variable.id),
        "name": "{} {}".format(variable.computer_cn, variable.name),
        "variable": form,
        "target_url": reverse("mgmt:edit_variable", args=[variable.id]),
        "action": "Modifier",
    })


@staff_member_required
def delete_variable(request, variable_id):
    models.Variable.objects.get(id=int(variable_id)).delete()
    return HttpResponseRedirect(redirect_to=reverse("mgmt:home"))


@staff_member_required
def list_variables(request):
    variables = models.Variable.objects.filter(
        computer_cn=""
    ).order_by("name")
    return render(request, 'mgmt_variables.html', {
        "variables": variables
    })


def get_computer_users(computer):
    assignments = models.ComputerAssignment.objects.filter(
        computer_cn=computer.cn
    )
    users = []
    for assignment in assignments:
        try:
            user = models.LdapUser.objects.get(cn=assignment.user_cn)
            users.append(user)
        except models.LdapUser.DoesNotExist:
            pass
    return users


def get_user_computers(username):
    assignments = models.ComputerAssignment.objects.filter(
        user_cn=username
    ).order_by("computer_cn")
    computers = []
    for assignment in assignments:
        try:
            computer = models.LdapComputer.objects.get(
                cn=assignment.computer_cn
            )
            computers.append(computer)
        except models.LdapComputer.DoesNotExist:
            pass
    return computers


def update_computer_users(computer, users):
    models.ComputerAssignment.objects.filter(computer_cn=computer.cn).delete()
    for user in users:
        a = models.ComputerAssignment(computer_cn=computer.cn, user_cn=user.cn)
        a.save()


def get_computer_roles(computer):
    assignments = models.RoleAssignment.objects.filter(
        computer_cn=computer.cn
    ).order_by("role__name")
    return [a.role for a in assignments]


def update_computer_roles(computer, roles):
    models.RoleAssignment.objects.filter(computer_cn=computer.cn).delete()
    for role in roles:
        models.RoleAssignment(computer_cn=computer.cn, role=role).save()


@staff_member_required
def create_computer(request):
    name = ""
    if request.method == "POST":
        form = forms.LdapComputerForm(request.POST)
        if form.is_valid():
            computer = form.save(commit=False)
            computer.cn = computer.user_name
            computer.home_directory = "/dev/null"
            computer.uid = get_next_ldap_uid_number(
                cls=models.LdapComputer, default=30000
            )
            computer.group = 30000
            computer.save()
            update_computer_users(computer, form.cleaned_data['users'])
            update_computer_roles(computer, form.cleaned_data['roles'])

farmer-web/mgmt/templates/mgmt_base.html
{% extends "base.html" %}

{% block title %}Administration - {% block mgmt_title %}{% endblock %}{%endblock %}

{% block body %}

<p><a href="{% url 'front:home' %}">Accueil</a>
{% if user.is_staff %}
&gt; <a href="{% url 'mgmt:home' %}">Administration</a>
{% else %}
&gt; <a href="{% url 'mgmt:show_user' %}">Espace utilisateur</a>
{% endif %}
{% block mgmt_path %}CHEMIN NON DEFINI{% endblock %}</p>

<hr/>

<h1>{% block mgmt_head %}{% endblock %}</h1>

{% block mgmt_body %}{% endblock %}

{% endblock %}

farmer-web/mgmt/templates/mgmt_computer_errors.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Erreurs et notifications de {{ name }}{% endblock %}
{% block mgmt_head %}Erreurs et notifications de {{ name }}{% endblock %}

{% block mgmt_path %}
&gt; <a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
&gt; <a href="{% url 'mgmt:edit_computer' name %}">Ordinateur {{ name }}</a>
&gt; Erreurs et notifications
{% endblock %}

{% block mgmt_body %}

<table>
	<tr>
		<th>Date</th>
	</tr>
	{% for error in errors %}
	<tr>
		<td>
			{% if not error.read %}
			<strong>
			{% endif %}
			<a href="{% url "mgmt:show_error" error.id %}">
				{{ error.date }}
			</a>
			{% if not error.read %}
			</strong>
			{% endif %}
		</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_computer_upgrades.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Mises à jour de {{ name }}{% endblock %}
{% block mgmt_head %}Mise à jour de {{ name }}{% endblock %}

{% block mgmt_path %}
&gt; <a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
&gt; <a href="{% url 'mgmt:edit_computer' name %}">Ordinateur {{ name }}</a>
&gt; Mises à jours
{% endblock %}

{% block mgmt_body %}

<table>
	<tr>
		<th>Date</th>
		<th>Paquet</th>
		<th>Version</th>
		<th>Commande</th>
	</tr>
	{% for upgrade in upgrades %}
	<tr>
		<td>{{ upgrade.date }}</td>
		<td>{{ upgrade.pkg }}</td>
		<td>{{ upgrade.version }}</td>
		<td>{{ upgrade.command }}</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_dmesg.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Dmesg {{ dmesg.computer_cn }} - {{ dmesg.date }}{% endblock %}
{% block mgmt_head %}Dmesg {{ dmesg.computer_cn }} - {{ dmesg.date }}{% endblock %}

{% block mgmt_path %}
&gt; <a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
&gt; <a href="{% url 'mgmt:edit_computer' name %}">Ordinateur {{ name }}</a>
&gt; <a href="{% url 'mgmt:show_computer_dmesgs' name %}">Dmesgs</a>
&gt; Dmesg {{ dmesg.computer_cn }} - {{ dmesg.date }}
{% endblock %}

{% block mgmt_body %}

<ul>
	<li>Ordinateur: <a href="{% url "mgmt:edit_computer" dmesg.computer_cn %}">{{ dmesg.computer_cn }}</a></li>
	<li>Date: {{ dmesg.date }}</li>
	<li>Traces:

<table>
	{% for k, v in content %}
	<tr>
		<td>{{ k }}</td>
		<td>{{ v }}</td>
	</tr>
	{% endfor %}
</table>

	</li>
</ul>


{% endblock %}

farmer-web/mgmt/templates/mgmt_error.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Erreur/notif. {{ error.computer_cn }} - {{ error.date }}{% endblock %}
{% block mgmt_head %}Erreur/notif. {{ error.computer_cn }} - {{ error.date }}{% endblock %}

{% block mgmt_path %}
&gt; <a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
&gt; <a href="{% url 'mgmt:edit_computer' name %}">Ordinateur {{ name }}</a>
&gt; <a href="{% url 'mgmt:show_computer_errors' name %}">Erreurs et notifications</a>
&gt; Erreur/notif. {{ error.computer_cn }} - {{ error.date }}
{% endblock %}

{% block mgmt_body %}

<ul>
	<li>Ordinateur: <a href="{% url "mgmt:edit_computer" error.computer_cn %}">{{ error.computer_cn }}</a></li>
	<li>Date: {{ error.date }}</li>
	<li>Traces:

{% if content.items %}
<table>
	{% for k, v in content.items %}
	<tr>
		<td>{{ k }}</td>
		<td><pre>{{ v }}</pre></td>
	</tr>
	{% endfor %}
</table>
{% else %}
<pre>
{{ content }}
</pre>
{% endif %}

	</li>
</ul>


{% endblock %}

farmer-web/mgmt/templates/mgmt_errors.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Erreurs et notifications{% endblock %}
{% block mgmt_head %}Erreurs et notifications{% endblock %}

{% block mgmt_path %}
> <a href="{% url 'mgmt:list_errors' %}">Erreurs et notifications</a>
{% endblock %}

{% block mgmt_body %}

{% if user.is_staff %}
<p>
<form action="{% url "mgmt:clear_errors" %}" method="POST">
	{% csrf_token %}
	<input type="submit" value="Tout marquer comme lu" />
</form>
</p>
{% endif %}


<table class="mgmt_errors">
	<tr>
		<th>Date</th>
		<th>Ordinateur</th>
	</tr>
	{% for error in errors %}
	<tr>
		<td>
			{% if not error.read %}
			<strong>
			{% endif %}
			<a href="{% url "mgmt:show_error" error.id %}">{{ error.date }}</a>
			{% if not error.read %}
			</strong>
			{% endif %}
		</td>
		<td><a href="{% url "mgmt:edit_computer" error.computer_cn %}">{{ error.computer_cn }}</a></td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_home.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Gestion{% endblock %}
{% block mgmt_head %}Gestion{% endblock %}

{% block mgmt_path %}{% endblock %}

{% block mgmt_body %}

<ul>
	<li>
		<a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
		<a href="{% url 'mgmt:create_computer' %}">[ajouter]</a>
	</li>
	<li>
		<a href="{% url 'mgmt:list_users' %}">Utilisateurs</a>
		<a href="{% url 'mgmt:create_user' %}">[ajouter]</a>
	</li>
	<li>
		<a href="{% url 'mgmt:list_roles' %}">Roles</a>
	</li>
	<li>
		{% if unread_errors %}
		<strong>
		{% endif %}
		<a href="{% url 'mgmt:list_errors' %}">Erreurs et notifications</a>
		{% if unread_errors %}
		({{ unread_errors }})
		</strong>
		{% endif %}
	</li>
	<li>
		<a href="{% url 'mgmt:list_variables' %}">Variables globales</a>
	</li>
	<li>
		<a href="{% url 'mgmt:list_servers' %}">Serveurs de stockage</a>
		<a href="{% url 'mgmt:create_server' %}">[ajouter]</a>
	</li>
</ul>

{% endblock %}

farmer-web/mgmt/templates/mgmt_roles.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Roles{% endblock %}
{% block mgmt_head %}Roles{% endblock %}

{% block mgmt_path %}
> <a href="{% url 'mgmt:list_roles' %}">Roles</a>
{% endblock %}

{% block mgmt_body %}

<p><a href="{% url 'mgmt:reload_roles' %}">[recharger depuis Git]</a></p>

<table class="mgmt_roles">
	<tr>
		<th>Identifiant</th>
	</tr>
	{% for role in roles %}
	<tr>
		<td>{{ role.name }}</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_servers.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Serveurs de stockage{% endblock %}
{% block mgmt_head %}Serveurs de stockage{% endblock %}

{% block mgmt_path %}
> <a href="{% url 'mgmt:list_servers' %}">Serveurs de stockage</a>
{% endblock %}

{% block mgmt_body %}

<p><a href="{% url 'mgmt:create_server' %}">[ajouter]</a></p>

<table class="mgmt_servers">
	<tr>
		<th>Nom</th>
		<th>Adresse</th>
	</tr>
	{% for server in servers %}
	<tr>
		<td>{{ server.nice_name }}</td>
		<td>{{ server.adress }}</td>
		<td>
			<a href="{% url "mgmt:edit_server" server.id %}">[voir]</a>
		</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_stats.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Statistiques de {{ name }}{% endblock %}
{% block mgmt_head %}Statistiques de {{ name }}{% endblock %}

{% block mgmt_path %}
&gt; <a href="{% url 'mgmt:list_computers' %}">Ordinateurs</a>
&gt; <a href="{% url 'mgmt:edit_computer' name %}">Ordinateur {{ name }}</a>
&gt; Statistiques
{% endblock %}

{% block mgmt_body %}

<table>
	<tr>
		<th>Date</th>
		<th>Nom</th>
		<th>Valeur</th>
	</tr>
	{% for statdate in stats %}
	<tr>
		<td>{{ statdate.date }}</td>
		<td></td>
		<td></td>
	</tr>
	{% for stat in statdate.stats %}
	<tr>
		<td></td>
		<td>{{ stat.name }}</td>
		<td>{{ stat.value }}</td>
		<td>
			<a href="{% url 'mgmt:show_stat' name stat.id %}">
				[historique]
			</a>
		</td>
	</tr>
	{% endfor %}
	{% endfor %}
</table>

{% endblock %}

farmer-web/mgmt/templates/mgmt_user.html
{% extends "mgmt_base.html" %}

{% block mgmt_title %}Utilisateur {{ name }}{% endblock %}
{% block mgmt_head %}Utilisateur {{ name }}{% endblock %}

{% block mgmt_path %}
> <a href="{% url 'mgmt:list_users' %}">Utilisateurs</a>
> Utilisateur {{ name }}
{% endblock %}

{% block mgmt_body %}

<form action="{{ target_url }}" method="POST">
	{% csrf_token %}
	<table class="tuxherding_form">
	{{ user.as_table }}
	</table>
	<input type="submit" value="{{ action }}" />
</form>

{% if computers %}
<h2>Ordinateurs associés</h2>

<table class="mgmt_computers">
	<tr>
		<th>Identifiant</th>
		<th>Nom</th>
		<th>Utilisateurs</th>
	</tr>
	{% for computer in computers %}
	<tr>
		<td>{{ computer.user_name }}</td>
		<td>{{ computer.full_name }}</td>
		<td>{{ computer.users|join:", " }}</td>
		<td>
			<a href="{% url "mgmt:edit_computer" computer.cn %}">[voir]</a>
		</td>
	</tr>
	{% endfor %}
</table>
{% endif %}

<h2>Suggestions de mot de passe</h2>
<ul>
	{% for password in suggested_passwords %}
	<li>{{ password }}</li>
	{% endfor %}
</ul>
{% endblock %}